variable "aws_region" {}
variable "environment" {}
variable "instance_type" {}
variable "key_name" {}
variable "project_name" {}
variable "albname" {}
variable "albtgname" {}
variable "alb_certificate_arn" {}
variable "nlbname" {}
variable "nlbtgname" {}
variable "domainname" {}
variable "rolename" {}
variable "instanceprofilename" {}
variable "iam_policy_name" {}
variable "db_subnet_group_name" {}
variable "db_name" {}
variable "nlb_recordname" {}
variable "alb_recordname" {}
variable "identifier" {}